default_language_version:
  python: python3.9
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.1
  hooks:
  - id: pyupgrade
    args: [--py39-plus]
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.14.1'
  hooks:
  - id: mypy
    additional_dependencies: [
	"numpy==2.0.2",
        "pillow==10.0.1",
    ]
    exclude: ^examples/|^tiffslide/tests/
- repo: https://github.com/PyCQA/flake8
  rev: '7.1.1'
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-typing-imports==1.15.0
    language_version: python3
    exclude: "^(build|docs|setup.py)|tests[/]"
- repo: https://github.com/PyCQA/bandit
  rev: '1.8.2'
  hooks:
  - id: bandit
    args: ["--ini", ".bandit", "-lll"]
