name: tiffslide ci

on: [push, pull_request]

jobs:
  # RUN PYTEST ON TIFFSLIDE SOURCE
  tests:
    name: pytest ${{ matrix.os }}::py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]
        include:
          # we'll test the python support on ubuntu
          - os: ubuntu-latest
            python-version: 3.9
          - os: ubuntu-latest
            python-version: 3.8
          - os: ubuntu-latest
            python-version: 3.7
    steps:
    - uses: actions/checkout@v1
    - name: Make python reference python3 because conda-devenv needs it
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Create the environment.yml via conda-devenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
    - name: Cache conda
      uses: actions/cache@v1
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('dev_environment.yml') }}
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: dev_environment.yml
        python-version: ${{ matrix.python-version }}
        auto-update-conda: true
        activate-environment: tiffslide
        use-only-tar-bz2: true
        auto-activate-base: false
    - shell: bash -l {0}
      name: Test with pytest
      run: |
        conda info
        conda list
        pytest

  # RUN MYPY STATIC TYPE ANALYSIS ON TIFFSLIDE SOURCE
  typing:
    name: mypy type analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install -e .[dev]
      - name: Run mypy
        run: |
          mypy --install-types --non-interactive --python-version=3.8 tiffslide

  # DEPLOY TIFFSLIDE TO TEST.PYPI ON SUCCESS
  testdeploy:
    needs: [tests, typing]
    name: deploy to test.pypi
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install pep517
        run: |
          python -m pip install --user build
      # we'll have to remove local_scheme for pushes to test.pypi pep440
      - name: Get version without local_scheme
        id: non_local_version
        run: |
          python setup.py --version | awk -F+ '{print "::set-output name=version::"$1}'
      - name: Build a binary wheel and a source tarball
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION: ${{ steps.non_local_version.outputs.version }}
        run: |
          python -m build .
      # push all versions on master to test.pypi.org
      - name: Publish package to TestPyPI
        continue-on-error: true
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/

  # DEPLOY TIFFSLIDE TO PYPI ON SUCCESS
  deploy:
    needs: [tests, typing]
    name: deploy to pypi
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install pep517
        run: |
          python -m pip install --user build
      - name: Build a binary wheel and a source tarball
        run: |
          python -m build .
      # push all tagged versions to pypi.org
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
