name: tiffslide ci

on: [push, pull_request]

jobs:
  # RUN PYTEST ON TIFFSLIDE SOURCE
  tests:
    name: pytest ${{ matrix.os }}::py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]
        include:
          # we'll test the python support on ubuntu
          - os: ubuntu-latest
            python-version: 3.8
    steps:
    - uses: actions/checkout@v1
    - name: Make python reference python3 because conda-devenv needs it
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Create the environment.yml via conda-devenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install git+https://github.com/ESSS/conda-devenv.git@2.1.1
        python -m conda_devenv.devenv --env TIFFSLIDE_DEVEL=TRUE --file environment.devenv.yml --print > environment.yml
    - name: Cache conda
      uses: actions/cache@v1
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
        auto-update-conda: true
        activate-environment: tiffslide
        use-only-tar-bz2: true
        auto-activate-base: false
    - shell: bash -l {0}
      name: Test with pytest
      run: |
        conda info
        conda list
        pytest
